const OPENROUTER_URL='https://openrouter.ai/api/v1/chat/completions';
const TURNSTILE_URL='https://challenges.cloudflare.com/turnstile/v0/siteverify';
const MODEL='openai/gpt-4o-mini';
const SITE_URL='https://amy2213.github.io/logical-steps-dashboard/';
const ORIGINS=new Set(['http://localhost:5173','https://amy2213.github.io']);
const ROLES=new Set(['context','premise','conclusion','assumption','counterpoint']);
const CONNECTIVES=new Set(['because','therefore','unless','but','if/then']);
const BAD_GISTS=new Set(['summary','gist','response','string','analysis']);
function cors(origin){return{...(origin&&ORIGINS.has(origin)?{'Access-Control-Allow-Origin':origin}:{}),'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Expose-Headers':'Retry-After,X-RateLimit-Limit,X-RateLimit-Remaining',Vary:'Origin'};}
function reply(body,status,origin,extra={}){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8',...cors(origin),...extra}});}
function parseJson(content){if(typeof content!=='string'||!content.trim())throw new Error('Empty model response.');return JSON.parse(content.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,''));}
function words(s){return String(s||'').toLowerCase().match(/[a-z0-9]+/g)||[];}
function similar(a,b){const aa=new Set(words(a)),bb=new Set(words(b));if(!aa.size||!bb.size)return 0;let common=0;for(const w of aa)if(bb.has(w))common++;return common/Math.max(aa.size,bb.size);}
function oneSentence(s){const t=String(s||'').trim().replace(/[.!?]\s*$/,'');return !/[.!?]\s+\S/.test(t);}
function validGist(g){if(typeof g!=='string')return false;const t=g.trim();return t.length>=20&&t.length<=180&&words(t).length>=4&&oneSentence(t)&&!BAD_GISTS.has(t.toLowerCase());}
function compactGist(text){const t=String(text||'').trim().replace(/\s+/g,' ');return t.length<=180?t:`${t.slice(0,177).trimEnd()}...`;}
function fallbackGist(nodes){const primary=nodes.find(n=>n.role==='conclusion'&&n.conclusionType==='primary')||nodes.find(n=>n.role==='conclusion')||nodes.find(n=>n.role==='premise')||nodes[0];return compactGist(primary?.plain||'The text explains several related claims, conditions, and outcomes.');}
function hasConcessionCue(text){return /\b(while proponents|while opponents|critics? (?:say|argue|claim)|opponents? (?:say|argue|claim)|supporters? (?:say|argue|claim)|some (?:say|argue|claim)|i understand|although .*?(?:say|argue|claim)|admittedly|to be fair)\b/i.test(text);}
function hasMiniArgumentCue(text){return /\b(if .+? then|therefore|thus|so,? |for that reason|which means|as a result)\b/i.test(text);}
function likelyArgument(text){return /\b(should|must|ought|therefore|thus|for that reason|we recommend|i recommend|the council should|the district should|we should|do not|don't|cannot conclude|can conclude)\b/i.test(text);}
function needsRepair(value,text){if(!validGist(value?.gist)||!Array.isArray(value?.nodes)||!value.nodes.length)return true;const nodes=value.nodes,conclusions=nodes.filter(n=>n?.role==='conclusion'),primary=conclusions.filter(n=>n?.conclusionType==='primary').length;if(likelyArgument(text)&&primary!==1)return true;if(!likelyArgument(text)&&primary>1)return true;if(hasConcessionCue(text)&&!nodes.some(n=>n?.role==='counterpoint'))return true;if(hasMiniArgumentCue(text)&&likelyArgument(text)&&conclusions.length<2&&nodes.length>=5)return true;if(text.length>700&&nodes.length<4)return true;return false;}
function normalize(value,sourceText,elapsedMs){
 if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Analysis must be an object.');
 if(!Array.isArray(value.nodes)||!value.nodes.length)throw new Error('Analysis nodes are missing.');
 const ids=new Set();
 const nodes=value.nodes.map((raw,i)=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error(`Node ${i+1} is invalid.`);const id=typeof raw.id==='string'&&raw.id.trim()?raw.id.trim():`n${i+1}`;if(ids.has(id))throw new Error('Node IDs must be unique.');ids.add(id);if(!ROLES.has(raw.role))throw new Error(`Unknown node role: ${raw.role}`);if(typeof raw.plain!=='string'||!raw.plain.trim())throw new Error('Every node requires plain text.');const original=typeof raw.original==='string'?raw.original.trim():'';const role=raw.role==='assumption'&&original?'premise':raw.role;const node={id,role,plain:raw.plain.trim(),original:role==='assumption'?'':original,dependsOn:Array.isArray(raw.dependsOn)?raw.dependsOn.filter(x=>typeof x==='string'):[]};if(role==='conclusion')node.conclusionType=raw.conclusionType==='primary'?'primary':'intermediate';if(typeof raw.confidence==='number'&&raw.confidence>=0&&raw.confidence<=1)node.confidence=raw.confidence;if(similar(node.plain,node.original)>=.9)node.original='';return node;});
 for(const node of nodes){node.dependsOn=node.dependsOn.filter(id=>ids.has(id)&&id!==node.id);const raw=value.nodes.find(n=>n?.id===node.id);if(node.dependsOn.length&&CONNECTIVES.has(raw?.connective))node.connective=raw.connective;}
 const conclusions=nodes.filter(n=>n.role==='conclusion');
 if(likelyArgument(sourceText)&&conclusions.length){const primary=conclusions.filter(n=>n.conclusionType==='primary');if(primary.length===0)conclusions[conclusions.length-1].conclusionType='primary';if(primary.length>1)for(const n of primary.slice(0,-1))n.conclusionType='intermediate';}
 if(!likelyArgument(sourceText))for(const n of conclusions)n.conclusionType='intermediate';
 const gist=validGist(value.gist)?value.gist.trim():fallbackGist(nodes);
 return{id:crypto.randomUUID(),sourceText,gist,nodes,meta:{model:MODEL,elapsedMs,mode:likelyArgument(sourceText)?'argument':'explanation'}};
}
function prompt(repair=false){return `You map dense text for neurodivergent readers. Return JSON only.${repair?' The previous answer missed content or forced the wrong structure; correct it carefully.':''}\nShape: {"gist":"one sentence, 20-180 characters","nodes":[{"id":"n1","role":"context|premise|conclusion|assumption|counterpoint","conclusionType":"primary|intermediate when role is conclusion","plain":"genuine plain-language rewrite","original":"exact source wording, or empty for assumptions","connective":"because|therefore|unless|but|if/then","dependsOn":[],"confidence":0.9}]}\nRules:\n- First decide whether the text is an argument or an explanation/report.\n- For an argument, identify exactly one primary conclusion. Use intermediate conclusions for supported sub-claims that support a later claim.\n- For an explanation or report, do not invent a main conclusion. It is valid to return zero conclusion nodes. Use context for scene-setting and premise for stated facts, requirements, causes, results, or constraints.\n- Cover every major idea in the source. Long passages should usually produce at least four nodes.\n- connective describes how THIS node follows from dependsOn; omit it when dependsOn is empty.\n- Counterpoint is a reported or conceded view the author does not endorse. Do not label the author's own warning or reason as counterpoint.\n- Add an assumption only when an unstated bridge is necessary. Assumptions must have original:"".\n- Rewrite substantially and conversationally; preserve uncertainty, numbers, and qualifiers.\n- Gist must be one concise sentence, 20-180 characters.`;}
function assumptionPrompt(){return `Find only necessary unstated assumptions in an already extracted argument. Return JSON only as {"assumptions":[{"plain":"one concise unstated bridge","supportsConclusionId":"existing conclusion id","dependsOn":["existing premise or intermediate-conclusion ids"],"confidence":0.0}]}. Return an empty assumptions array when the stated reasons already support the conclusion without a necessary hidden bridge. Never restate a premise or conclusion. Never infer background trivia, motives, predictions, or merely helpful facts. Each assumption must be required for the inference, have confidence at least 0.75, and use only supplied node IDs.`;}
async function modelRequest(env,messages,max_tokens=2400){const r=await fetch(OPENROUTER_URL,{method:'POST',headers:{Authorization:`Bearer ${env.OPENROUTER_API_KEY}`,'Content-Type':'application/json','HTTP-Referer':SITE_URL,'X-OpenRouter-Title':'Logical Steps Dashboard'},body:JSON.stringify({model:MODEL,temperature:.1,max_tokens,response_format:{type:'json_object'},messages})});const raw=await r.text();if(!r.ok)throw Object.assign(new Error('The analysis provider rejected the request.'),{status:r.status,detail:raw.slice(0,500)});return parseJson(JSON.parse(raw)?.choices?.[0]?.message?.content);}
async function callModel(env,text,repair=false){return modelRequest(env,[{role:'system',content:prompt(repair)},{role:'user',content:text}]);}
async function callAssumptions(env,analysis){const compact=analysis.nodes.filter(n=>['premise','conclusion','counterpoint'].includes(n.role)).map(n=>({id:n.id,role:n.role,conclusionType:n.conclusionType,plain:n.plain,dependsOn:n.dependsOn}));return modelRequest(env,[{role:'system',content:assumptionPrompt()},{role:'user',content:JSON.stringify({sourceText:analysis.sourceText,nodes:compact})}],700);}
function mergeAssumptions(analysis,result){if(!Array.isArray(result?.assumptions)||analysis.nodes.some(n=>n.role==='assumption'))return analysis;const ids=new Set(analysis.nodes.map(n=>n.id));const conclusions=new Map(analysis.nodes.filter(n=>n.role==='conclusion').map(n=>[n.id,n]));const additions=[];for(const raw of result.assumptions.slice(0,3)){if(!raw||typeof raw.plain!=='string'||raw.plain.trim().length<12||typeof raw.confidence!=='number'||raw.confidence<.75)continue;const target=conclusions.get(raw.supportsConclusionId);if(!target)continue;const dependsOn=Array.isArray(raw.dependsOn)?raw.dependsOn.filter(id=>ids.has(id)&&id!==target.id):[];if(!dependsOn.length)continue;if(analysis.nodes.some(n=>similar(n.plain,raw.plain)>=.72)||additions.some(n=>similar(n.plain,raw.plain)>=.72))continue;let id=`a${additions.length+1}`;while(ids.has(id))id=`a${additions.length+2}`;ids.add(id);additions.push({id,role:'assumption',plain:raw.plain.trim(),original:'',dependsOn,connective:'because',confidence:raw.confidence});target.dependsOn=[...new Set([...target.dependsOn,id])];if(!target.connective)target.connective='therefore';}
 return additions.length?{...analysis,nodes:[...analysis.nodes,...additions],meta:{...analysis.meta,assumptionPass:true}}:analysis;}
async function verifyTurnstile(env,token,ip){if(!env.TURNSTILE_SECRET_KEY)return true;if(typeof token!=='string'||!token)return false;const r=await fetch(TURNSTILE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:env.TURNSTILE_SECRET_KEY,response:token,remoteip:ip})});return Boolean((await r.json()).success);}
async function takeLimit(env,name,key,limit,windowMs){const id=env.RATE_LIMITER.idFromName(name);const r=await env.RATE_LIMITER.get(id).fetch('https://limit.local/take',{method:'POST',body:JSON.stringify({key,limit,windowMs})});return r.json();}
export class RateLimiter{constructor(state){this.state=state;}async fetch(request){const {key,limit,windowMs}=await request.json();const now=Date.now();const record=await this.state.storage.get(key)||{start:now,count:0};if(now-record.start>=windowMs){record.start=now;record.count=0;}record.count++;await this.state.storage.put(key,record);const reset=Math.max(1,Math.ceil((record.start+windowMs-now)/1000));return Response.json({allowed:record.count<=limit,remaining:Math.max(0,limit-record.count),reset});}}
export default{async fetch(request,env){
 const started=Date.now(),origin=request.headers.get('Origin'),url=new URL(request.url);
 if(request.method==='OPTIONS'){if(!origin||!ORIGINS.has(origin))return new Response(null,{status:403});return new Response(null,{status:204,headers:cors(origin)});}
 if(url.pathname==='/health'&&request.method==='GET')return reply({ok:true,service:'logical-steps-api'},200,origin);
 if(url.pathname!=='/v1/analyze'||request.method!=='POST')return reply({error:{code:'NOT_FOUND',message:'Route not found.'}},404,origin);
 if(origin&&!ORIGINS.has(origin))return reply({error:{code:'ORIGIN_NOT_ALLOWED',message:'This origin is not allowed.'}},403,origin);
 if(!env.OPENROUTER_API_KEY||!env.RATE_LIMITER)return reply({error:{code:'SERVER_CONFIGURATION_ERROR',message:'The analysis service is not configured.'}},500,origin);
 let body;try{body=await request.json();}catch{return reply({error:{code:'INVALID_JSON',message:'Request body must be valid JSON.'}},400,origin);}
 const text=typeof body?.text==='string'?body.text.trim():'';if(!text)return reply({error:{code:'INVALID_TEXT',message:'A non-empty text field is required.'}},400,origin);if(text.length>12000)return reply({error:{code:'TEXT_TOO_LONG',message:'Text must be 12,000 characters or fewer.'}},413,origin);
 const ip=request.headers.get('CF-Connecting-IP')||'unknown';
 const human=await verifyTurnstile(env,body.turnstileToken,ip);if(!human)return reply({error:{code:'HUMAN_VERIFICATION_FAILED',message:'Please complete the human verification and try again.'}},403,origin);
 const perIp=await takeLimit(env,`ip:${ip}`,ip,10,10*60*1000);if(!perIp.allowed)return reply({error:{code:'RATE_LIMITED',message:'Too many analyses from this connection. Please wait before trying again.'}},429,origin,{'Retry-After':String(perIp.reset),'X-RateLimit-Limit':'10','X-RateLimit-Remaining':'0'});
 const global=await takeLimit(env,'global-daily','all',300,24*60*60*1000);if(!global.allowed)return reply({error:{code:'DAILY_LIMIT_REACHED',message:'Logical Steps has reached its daily analysis limit. Please try again tomorrow.'}},429,origin,{'Retry-After':String(global.reset)});
 try{let model=await callModel(env,text,false);if(needsRepair(model,text))model=await callModel(env,text,true);let analysis=normalize(model,text,Date.now()-started);if(analysis.meta.mode==='argument'&&!analysis.nodes.some(n=>n.role==='assumption')){try{analysis=mergeAssumptions(analysis,await callAssumptions(env,analysis));}catch(error){console.warn('Assumption pass failed',{message:error instanceof Error?error.message:'Unknown error'});}}analysis.meta.elapsedMs=Date.now()-started;return reply(analysis,200,origin,{'X-RateLimit-Limit':'10','X-RateLimit-Remaining':String(perIp.remaining)});}catch(error){console.error('Analysis failed',{message:error instanceof Error?error.message:'Unknown error',detail:error?.detail});return reply({error:{code:error?.status?'UPSTREAM_ERROR':'INVALID_ANALYSIS',message:error?.status?'The analysis provider could not complete this request.':'The provider returned an invalid logical map.'}},502,origin);}
}};